[package]
name = "r-device"
version = "0.1.0"
authors = ["Didrik Rokhaug <didrik.rokhaug@gmail.com>"]

[dependencies]
rumqtt = "*"
#jsonwebtoken = "4"
frank_jwt = "*"
serde_derive = "1"
serde = "1"
serde_json = "1"